# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

createBaseInfoCpp <- function(num_chroms, num_markers, cM, bp, seed) {
    .Call(`_BitBreedingSim_createBaseInfoCpp`, num_chroms, num_markers, cM, bp, seed)
}

createBaseInfoWithMap <- function(chrom_maps, seed) {
    .Call(`_BitBreedingSim_createBaseInfoWithMap`, chrom_maps, seed)
}

getNumChroms <- function(ptr) {
    .Call(`_BitBreedingSim_getNumChroms`, ptr)
}

getNumTraits <- function(ptr) {
    .Call(`_BitBreedingSim_getNumTraits`, ptr)
}

getTraitCpp <- function(baseInfoPtr, i) {
    .Call(`_BitBreedingSim_getTraitCpp`, baseInfoPtr, i)
}

add_Trait_A_wrapper <- function(ptr, name, mean, h2, sd_ = NULL, a = NULL, loci = NULL, num_loci = 1L) {
    invisible(.Call(`_BitBreedingSim_add_Trait_A_wrapper`, ptr, name, mean, h2, sd_, a, loci, num_loci))
}

add_Trait_AD_wrapper <- function(baseInfoPtr, name, mean, sd_ = NULL, h2_ = NULL, H2_ = NULL, a = NULL, ds = NULL, loci = NULL, num_loci = 1L) {
    invisible(.Call(`_BitBreedingSim_add_Trait_AD_wrapper`, baseInfoPtr, name, mean, sd_, h2_, H2_, a, ds, loci, num_loci))
}

createOrigins <- function(num_inds, info, name_base) {
    .Call(`_BitBreedingSim_createOrigins`, num_inds, info, name_base)
}

crossPops <- function(num_inds, mothers, fathers, name_base, T) {
    .Call(`_BitBreedingSim_crossPops`, num_inds, mothers, fathers, name_base, T)
}

getNumInds <- function(pop) {
    .Call(`_BitBreedingSim_getNumInds`, pop)
}

getNumChromsPop <- function(pop) {
    .Call(`_BitBreedingSim_getNumChromsPop`, pop)
}

getPhenotypesCpp <- function(pop, i) {
    .Call(`_BitBreedingSim_getPhenotypesCpp`, pop, i)
}

selectPop <- function(pop, indices_R) {
    .Call(`_BitBreedingSim_selectPop`, pop, indices_R)
}

getGenotypes <- function(pop) {
    .Call(`_BitBreedingSim_getGenotypes`, pop)
}

getGenotypes_naive <- function(pop) {
    .Call(`_BitBreedingSim_getGenotypes_naive`, pop)
}

getPhasedGenotypes <- function(pop) {
    .Call(`_BitBreedingSim_getPhasedGenotypes`, pop)
}

getPhasedIntGenotypes <- function(pop) {
    .Call(`_BitBreedingSim_getPhasedIntGenotypes`, pop)
}

getPopulationInfo <- function(popPtr) {
    .Call(`_BitBreedingSim_getPopulationInfo`, popPtr)
}

