# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

createBaseInfo <- function(seed) {
    .Call(`_BitBreedingSim_createBaseInfo`, seed)
}

getNumChroms <- function(ptr) {
    .Call(`_BitBreedingSim_getNumChroms`, ptr)
}

getNumTraits <- function(ptr) {
    .Call(`_BitBreedingSim_getNumTraits`, ptr)
}

setTrait <- function(ptr) {
    invisible(.Call(`_BitBreedingSim_setTrait`, ptr))
}

setTraitADMulti <- function(ptr, num_loci, h2, H2) {
    invisible(.Call(`_BitBreedingSim_setTraitADMulti`, ptr, num_loci, h2, H2))
}

createOrigins <- function(num_inds, info, name_base) {
    .Call(`_BitBreedingSim_createOrigins`, num_inds, info, name_base)
}

cross <- function(num_inds, mothers, fathers, info, name_base, T) {
    .Call(`_BitBreedingSim_cross`, num_inds, mothers, fathers, info, name_base, T)
}

getNumInds <- function(ptr) {
    .Call(`_BitBreedingSim_getNumInds`, ptr)
}

getPopNumChroms <- function(ptr) {
    .Call(`_BitBreedingSim_getPopNumChroms`, ptr)
}

getPhenotypes <- function(population, i) {
    .Call(`_BitBreedingSim_getPhenotypes`, population, i)
}

selectPop <- function(population, indices) {
    .Call(`_BitBreedingSim_selectPop`, population, indices)
}

