# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

createBaseInfoCpp <- function(pos, cM, seed) {
    .Call(`_BitBreedingSim_createBaseInfoCpp`, pos, cM, seed)
}

createBaseInfoWithMap <- function(pos, chrom_maps, seed) {
    .Call(`_BitBreedingSim_createBaseInfoWithMap`, pos, chrom_maps, seed)
}

getNumChroms <- function(ptr) {
    .Call(`_BitBreedingSim_getNumChroms`, ptr)
}

getNumTraits <- function(ptr) {
    .Call(`_BitBreedingSim_getNumTraits`, ptr)
}

getNumAllMarkers <- function(ptr) {
    .Call(`_BitBreedingSim_getNumAllMarkers`, ptr)
}

getNumMarkers <- function(ptr, i) {
    .Call(`_BitBreedingSim_getNumMarkers`, ptr, i)
}

getTraitCpp <- function(baseInfoPtr, i) {
    .Call(`_BitBreedingSim_getTraitCpp`, baseInfoPtr, i)
}

getMapfromInfo <- function(baseInfoPtr) {
    .Call(`_BitBreedingSim_getMapfromInfo`, baseInfoPtr)
}

add_Trait_A_wrapper <- function(ptr, name, mean, h2, sd_ = NULL, a = NULL, loci = NULL, num_loci = 1L) {
    invisible(.Call(`_BitBreedingSim_add_Trait_A_wrapper`, ptr, name, mean, h2, sd_, a, loci, num_loci))
}

add_Trait_AD_wrapper <- function(baseInfoPtr, name, mean, sd_ = NULL, h2_ = NULL, H2_ = NULL, a = NULL, ds = NULL, loci = NULL, num_loci = 1L) {
    invisible(.Call(`_BitBreedingSim_add_Trait_AD_wrapper`, baseInfoPtr, name, mean, sd_, h2_, H2_, a, ds, loci, num_loci))
}

getMapInfo <- function(mapPtr) {
    .Call(`_BitBreedingSim_getMapInfo`, mapPtr)
}

getMapCpp <- function(mapPtr) {
    .Call(`_BitBreedingSim_getMapCpp`, mapPtr)
}

readVCF <- function(filename) {
    .Call(`_BitBreedingSim_readVCF`, filename)
}

createOrigins <- function(num_inds, info, name_base) {
    .Call(`_BitBreedingSim_createOrigins`, num_inds, info, name_base)
}

createInfoAndPopFromVCF <- function(vcf, seed) {
    .Call(`_BitBreedingSim_createInfoAndPopFromVCF`, vcf, seed)
}

createPopFromHaploArray <- function(haploArray, info) {
    .Call(`_BitBreedingSim_createPopFromHaploArray`, haploArray, info)
}

createHaploArrayFromPop <- function(pop_ptr) {
    .Call(`_BitBreedingSim_createHaploArrayFromPop`, pop_ptr)
}

setSampleNames <- function(names_, pop_ptr) {
    invisible(.Call(`_BitBreedingSim_setSampleNames`, names_, pop_ptr))
}

crossPopsRandomly <- function(num_inds, mothers, fathers, name_base, names, T) {
    .Call(`_BitBreedingSim_crossPopsRandomly`, num_inds, mothers, fathers, name_base, names, T)
}

crossPopsByTable <- function(df, mothers, fathers, name_base, T) {
    .Call(`_BitBreedingSim_crossPopsByTable`, df, mothers, fathers, name_base, T)
}

writeVCF <- function(pop, filename) {
    invisible(.Call(`_BitBreedingSim_writeVCF`, pop, filename))
}

getNumInds <- function(pop) {
    .Call(`_BitBreedingSim_getNumInds`, pop)
}

getNumChromsPop <- function(pop) {
    .Call(`_BitBreedingSim_getNumChromsPop`, pop)
}

getPhenotypesCpp <- function(pop, i) {
    .Call(`_BitBreedingSim_getPhenotypesCpp`, pop, i)
}

selectPop <- function(pop, indices_R) {
    .Call(`_BitBreedingSim_selectPop`, pop, indices_R)
}

getGenotypes <- function(pop) {
    .Call(`_BitBreedingSim_getGenotypes`, pop)
}

getGenotypes_naive <- function(pop) {
    .Call(`_BitBreedingSim_getGenotypes_naive`, pop)
}

getPhasedGenotypes <- function(pop) {
    .Call(`_BitBreedingSim_getPhasedGenotypes`, pop)
}

getPhasedIntGenotypes <- function(pop) {
    .Call(`_BitBreedingSim_getPhasedIntGenotypes`, pop)
}

getPopulationInfo <- function(pop) {
    .Call(`_BitBreedingSim_getPopulationInfo`, pop)
}

createNameDataFromPop <- function(pop) {
    .Call(`_BitBreedingSim_createNameDataFromPop`, pop)
}

joinPop <- function(pop1, pop2) {
    .Call(`_BitBreedingSim_joinPop`, pop1, pop2)
}

